/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ElitesDuBacRouteImport } from './routes/elites-du-bac'
import { Route as TemoignagesRouteImport } from './routes/temoignages'
import { Route as UvsVoyagesRouteImport } from './routes/uvs-voyages'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ElitesDuBacRoute = ElitesDuBacRouteImport.update({
  id: '/elites-du-bac',
  path: '/elites-du-bac',
  getParentRoute: () => rootRouteImport,
} as any)
const TemoignagesRoute = TemoignagesRouteImport.update({
  id: '/temoignages',
  path: '/temoignages',
  getParentRoute: () => rootRouteImport,
} as any)
const UvsVoyagesRoute = UvsVoyagesRouteImport.update({
  id: '/uvs-voyages',
  path: '/uvs-voyages',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/elites-du-bac': typeof ElitesDuBacRoute
  '/temoignages': typeof TemoignagesRoute
  '/uvs-voyages': typeof UvsVoyagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/elites-du-bac': typeof ElitesDuBacRoute
  '/temoignages': typeof TemoignagesRoute
  '/uvs-voyages': typeof UvsVoyagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/elites-du-bac': typeof ElitesDuBacRoute
  '/temoignages': typeof TemoignagesRoute
  '/uvs-voyages': typeof UvsVoyagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/elites-du-bac'
    | '/temoignages'
    | '/uvs-voyages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/elites-du-bac'
    | '/temoignages'
    | '/uvs-voyages'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/contact'
    | '/elites-du-bac'
    | '/temoignages'
    | '/uvs-voyages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ContactRoute: typeof ContactRoute
  ElitesDuBacRoute: typeof ElitesDuBacRoute
  TemoignagesRoute: typeof TemoignagesRoute
  UvsVoyagesRoute: typeof UvsVoyagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elites-du-bac': {
      id: '/elites-du-bac'
      path: '/elites-du-bac'
      fullPath: '/elites-du-bac'
      preLoaderRoute: typeof ElitesDuBacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temoignages': {
      id: '/temoignages'
      path: '/temoignages'
      fullPath: '/temoignages'
      preLoaderRoute: typeof TemoignagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uvs-voyages': {
      id: '/uvs-voyages'
      path: '/uvs-voyages'
      fullPath: '/uvs-voyages'
      preLoaderRoute: typeof UvsVoyagesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ContactRoute: ContactRoute,
  ElitesDuBacRoute: ElitesDuBacRoute,
  TemoignagesRoute: TemoignagesRoute,
  UvsVoyagesRoute: UvsVoyagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
